export const PLAN_CONSTANTS = {
    TYPE_RECURRING: 'RECURRING',
    TYPE_ONETIME: 'ONETIME',
    INTERVAL_30_DAYS: 'EVERY_30_DAYS',
    INTERVAL_EVERY_YEARLY: 'ANNUAL',
    REF_FREEMIUM: 'FREEMIUM',
    REF_STANDARD: 'STANDARD',
    REF_PREMIUM: 'PREMIUM'
}